@startuml

skinparam classAttributeIconSize 0

interface ReferenceLineSmoother {
    + virtual void SetAnchorPoints(const std::vector<AnchorPoint>& achor_points) = 0
    + virtual bool Smooth(const ReferenceLine&, ReferenceLine* const) = 0
    # ReferenceLineSmootherConfig config_
}

class DiscretePointsReferenceLineSmoother
class QpSplineReferenceLineSmoother
class SpiralReferenceLineSmoother

ReferenceLineSmoother <|.. DiscretePointsReferenceLineSmoother
ReferenceLineSmoother <|.. QpSplineReferenceLineSmoother
ReferenceLineSmoother <|.. SpiralReferenceLineSmoother

@enduml
